import { useState } from 'react';
import './App.css';
import "./output.css";

export default function App() {
  const cards = [
    { q: "What does a red light mean?", a: "Stop completely." },
    { q: "What color are work zone signs?", a: "Orange." },
    { q: "Shape of a stop sign?", a: "Octagon." },
    { q: "Minimum BAC for DUI (21+)?", a: "0.08%" },
    { q: "Speed limit in a school zone?", a: "25 mph." },
    { q: "What is the minimum age for a learner’s permit in Virginia?", a: "15 years and 6 months." },
    { q: "How many parts does the Virginia knowledge exam have?", a: "Two — a traffic signs section and a general knowledge section." },
{ q: "What must you pass before taking the general knowledge portion?", a: "The traffic signs portion." },
{ q: "What happens if you fail the traffic signs part of the test?", a: "You cannot take the general knowledge part that day." },
{ q: "What is required to take the road skills test?", a: "You must pass the knowledge test and vision screening first." },
{ q: "What is the purpose of the vision screening?", a: "To ensure you meet the minimum vision standards for safe driving." },
{ q: "What vision must you have to pass the DMV vision test?", a: "At least 20/40 vision in one or both eyes." },
{ q: "What horizontal vision field must you have in Virginia?", a: "At least 110 degrees." },
{ q: "Can you wear glasses or contact lenses for the vision test?", a: "Yes, but your license will show that corrective lenses are required." },
{ q: "What happens if you fail the DMV vision test?", a: "You must see an eye specialist and may need to retake the screening." },
{ q: "When can you take the road skills test?", a: "After passing the knowledge and vision tests." },
{ q: "What does a red light mean?", a: "Come to a complete stop before the crosswalk or stop line." },
{ q: "What should you do at a flashing red light?", a: "Stop completely, then go when it's safe." },
{ q: "What does a yellow light mean?", a: "The light is about to turn red; prepare to stop." },
{ q: "What does a flashing yellow light mean?", a: "Slow down and proceed with caution." },
{ q: "What does a green light mean?", a: "Proceed through the intersection if the way is clear." },
{ q: "What does a red arrow mean?", a: "You may not turn in that direction until the light turns green." },
{ q: "What does a flashing red arrow mean?", a: "Stop completely, then turn in that direction when safe." },
{ q: "What does a green arrow mean?", a: "You have a protected turn; oncoming traffic must yield." },
{ q: "What does a flashing yellow arrow mean?", a: "You may turn with caution but must yield to oncoming traffic." },
{ q: "If traffic lights are out, how should you treat the intersection?", a: "As a four-way stop; everyone must yield and proceed carefully." },
{ q: "What shape is a stop sign?", a: "Octagon (eight sides)." },
{ q: "What shape is a yield sign?", a: "Triangle pointing downward." },
{ q: "What shape is a warning sign?", a: "Diamond." },
{ q: "What shape is a railroad crossing sign?", a: "Circle." },
{ q: "What shape is a school zone or crossing sign?", a: "Pentagon." },
{ q: "What shape is a regulatory or guide sign?", a: "Rectangle (vertical or horizontal)." },
{ q: "What shape is used for no passing zone warnings?", a: "Pennant (sideways triangle)." },
{ q: "What shape indicates a route marker?", a: "Shield." },
{ q: "What shape shows an evacuation route?", a: "A blue-and-white rectangle." },
{ q: "What shape do stop and yield signs always have?", a: "Unique shapes for instant recognition even if damaged." },
{ q: "What does a red sign mean?", a: "Stop, yield, or do not enter." },
{ q: "What does a yellow sign mean?", a: "Warning — be alert to hazards ahead." },
{ q: "What does a green sign indicate?", a: "Direction or distance information." },
{ q: "What does a blue sign indicate?", a: "Motorist services such as gas, food, or lodging." },
{ q: "What does a brown sign indicate?", a: "Historical or recreational area." },
{ q: "What does an orange sign indicate?", a: "Work zone or temporary traffic control." },
{ q: "What does a white or black sign indicate?", a: "Regulatory or law-based information." },
{ q: "What color combination marks school zones?", a: "Fluorescent yellow-green." },
{ q: "What color is used for incident management signs?", a: "Pink." },
{ q: "What color is used for guide signs showing exits or directions?", a: "Green with white letters." },
{ q: "What does a 'Do Not Enter' sign mean?", a: "You cannot drive on that road in the direction you're going." },
{ q: "What does a 'Wrong Way' sign mean?", a: "You are driving against traffic; turn around immediately." },
{ q: "What does a 'One Way' sign indicate?", a: "Traffic moves only in the direction of the arrow." },
{ q: "What does a 'No U-Turn' sign mean?", a: "You may not make a U-turn at that location." },
{ q: "What does a 'Speed Limit' sign indicate?", a: "The maximum legal speed under ideal conditions." },
{ q: "What does a 'Left Turn Yield on Green' sign mean?", a: "You may turn left but must yield to oncoming traffic." },
{ q: "What does a 'Keep Right' sign mean?", a: "Stay to the right of the divider or obstacle." },
{ q: "What does a 'No Parking' sign mean?", a: "You may stop briefly to load or unload but not park." },
{ q: "What does a 'Stop' sign require?", a: "A full stop at the stop line, crosswalk, or intersection before proceeding." },
{ q: "What does a 'Yield' sign mean?", a: "Slow down and give right of way to traffic and pedestrians before proceeding." },
{ q: "What do yellow diamond-shaped signs usually mean?", a: "They warn about special road hazards or conditions ahead." },
{ q: "What does a 'Slippery When Wet' sign indicate?", a: "The roadway is slippery in wet weather; slow down." },
{ q: "What does a 'Merge' sign mean?", a: "Traffic from another road will be joining yours; adjust speed or change lanes safely." },
{ q: "What does a 'Divided Highway Begins' sign mean?", a: "The road ahead will be divided by a median; keep right." },
{ q: "What does a 'Divided Highway Ends' sign mean?", a: "The divided roadway ends; traffic from both directions will share the road." },
{ q: "What does a 'Two-Way Traffic' sign indicate?", a: "The road ahead carries traffic in both directions." },
{ q: "What does a 'Curve Ahead' sign mean?", a: "A curve is coming up; reduce speed." },
{ q: "What does a 'Winding Road' sign mean?", a: "Several curves ahead; drive carefully." },
{ q: "What does a 'Pedestrian Crossing' sign mean?", a: "Pedestrians may cross the road ahead; be prepared to stop." },
{ q: "What does a 'Deer Crossing' sign mean?", a: "Watch for animals crossing the road; slow down and stay alert." },
{ q: "What does a 'School Zone' sign mean?", a: "You're near a school; reduce speed and watch for children." },
{ q: "What does a 'Hill' sign mean?", a: "A steep slope is ahead; check brakes and shift to a lower gear if necessary." },
{ q: "What does a 'Narrow Bridge' sign indicate?", a: "The bridge ahead is narrower than the roadway; slow down and use caution." },
{ q: "What does a 'Crossroad' sign indicate?", a: "An intersection is ahead; watch for crossing traffic." },
{ q: "What does a 'Traffic Signal Ahead' sign warn?", a: "There's a traffic light ahead; be prepared to stop." },
{ q: "What does a 'Stop Ahead' sign mean?", a: "A stop sign is ahead; slow down and prepare to stop." },
{ q: "What does a 'Yield Ahead' sign mean?", a: "A yield sign is coming; slow down and prepare to yield." },
{ q: "What does a 'Low Clearance' sign warn about?", a: "The overhead clearance is limited; make sure your vehicle can fit." },
{ q: "What does a 'No Passing Zone' pennant mean?", a: "Passing is not allowed on that stretch of road." },
{ q: "What does a 'Roundabout Ahead' sign mean?", a: "You're approaching a circular intersection; slow down and yield to traffic inside." },
{ q: "What color are work zone signs?", a: "Orange with black letters or symbols." },
{ q: "What do orange cones and barrels indicate?", a: "Temporary lane closures or changes in traffic patterns." },
{ q: "What should you do in a work zone?", a: "Slow down, obey posted signs, and follow directions from flaggers." },
{ q: "What happens if you speed in a work zone?", a: "Fines are doubled." },
{ q: "What should you do if you see a worker or equipment on the road?", a: "Yield and be prepared to stop." },
{ q: "When is a driver cited for reckless driving in a work zone?", a: "When driving 15 mph or more over the posted limit." },
{ q: "Are cell phones allowed in work zones?", a: "Handheld phone use is prohibited; hands-free only." },
{ q: "What shape or color do flagger signs have?", a: "Orange diamond signs showing a person with a flag or STOP/SLOW paddle." },
{ q: "If a flagger signals you to stop, what must you do?", a: "Stop as directed and proceed only when instructed." },
{ q: "When approaching a lane closure in a work zone, what is safest?", a: "Merge early and avoid last-minute lane changes." },
{ q: "What do yellow lines separate?", a: "Traffic moving in opposite directions." },
{ q: "What do white lines separate?", a: "Traffic moving in the same direction." },
{ q: "What does a broken yellow line mean?", a: "Passing is allowed when clear." },
{ q: "What does a solid yellow line mean?", a: "No passing from your lane." },
{ q: "What do double solid yellow lines mean?", a: "No passing from either direction." },
{ q: "What does a solid white line mean?", a: "Stay in your lane; lane changes are discouraged." },
{ q: "What does a broken white line mean?", a: "Lane changes are permitted with caution." },
{ q: "What do diagonal white stripes in a lane mean?", a: "The area is not for driving; it separates traffic or guides merging." },
{ q: "What do arrows painted on the pavement mean?", a: "Indicate the direction(s) of travel from that lane." },
{ q: "What do painted curbs mean in Virginia?", a: "They indicate parking restrictions (red = no parking, yellow = loading zone, blue = disabled)." },
{ q: "What is the correct hand position on the steering wheel?", a: "9 and 3 o'clock positions." },
{ q: "What should you do at a stop sign?", a: "Come to a complete stop at the stop line or crosswalk." },
{ q: "What is the maximum speed limit on most highways in Virginia?", a: "55 mph unless otherwise posted." },
{ q: "What is the maximum speed limit on interstate highways?", a: "65 to 70 mph depending on the location." },
{ q: "What is the speed limit in school or residential zones?", a: "25 mph unless posted otherwise." },
{ q: "What is the minimum speed on an interstate?", a: "Generally 45 mph if safe conditions allow." },
{ q: "What is the speed limit in business zones?", a: "25 mph." },
{ q: "When must you yield to pedestrians?", a: "Always at crosswalks and intersections." },
{ q: "When approaching a flashing yellow light, what should you do?", a: "Slow down and proceed with caution." },
{ q: "What is the 'basic speed law'?", a: "You must drive no faster than conditions allow, regardless of posted limits." },
{ q: "Who has the right-of-way at an uncontrolled intersection?", a: "The driver on the right." },
{ q: "What should you do when entering a roundabout?", a: "Yield to vehicles already in the circle." },
{ q: "What should you do when exiting a roundabout?", a: "Signal right as you leave." },
{ q: "When should you use turn signals before turning or changing lanes?", a: "At least 100 feet in advance." },
{ q: "What should you always check before changing lanes?", a: "Mirrors and blind spots." },
{ q: "What is the 'three-second rule'?", a: "Stay at least three seconds behind the vehicle ahead." },
{ q: "When should you increase your following distance?", a: "In rain, fog, snow, or behind large vehicles." },
{ q: "How do you check your blind spot?", a: "Turn your head and look over your shoulder." },
{ q: "What should you do if another driver tailgates you?", a: "Move to another lane or slow down gradually to encourage them to pass." },
{ q: "When should you not pass another vehicle?", a: "On hills, curves, intersections, or when a solid line is on your side." },
{ q: "What is a 'space cushion'?", a: "The area around your vehicle that gives room to react to danger." },
{ q: "How far ahead should you look while driving?", a: "About 20–30 seconds ahead." },
{ q: "What should you do when being passed?", a: "Stay in your lane and do not speed up." },
{ q: "When driving near large trucks, where are their blind spots?", a: "Directly behind, in front, and along both sides." },
{ q: "Why is it dangerous to linger beside a truck?", a: "The driver may not see you when changing lanes." },
{ q: "What should you do before backing out of a driveway or parking spot?", a: "Look behind you and check mirrors before moving." },
{ q: "What direction should you look when backing up straight?", a: "Turn your head and look through the rear window." },
{ q: "Is it legal to back up on an interstate or highway?", a: "No, it’s illegal and extremely dangerous." },
{ q: "How do you park uphill with a curb?", a: "Turn the front wheels away from the curb." },
{ q: "How do you park downhill with a curb?", a: "Turn the front wheels toward the curb." },
{ q: "What is 'distracted driving'?", a: "Driving while focusing on anything other than the road, such as texting, eating, or adjusting the radio." },
{ q: "Is it illegal to hold a cellphone while driving in Virginia?", a: "Yes, handheld phone use is banned; only hands-free is allowed." },
{ q: "What is 'aggressive driving'?", a: "Behaviors like tailgating, weaving through traffic, or yelling at other drivers." },
{ q: "What should you do if another driver acts aggressively toward you?", a: "Stay calm, avoid eye contact, and do not respond." },
{ q: "What is 'road rage'?", a: "Extreme aggressive behavior such as chasing, ramming, or physically confronting another driver." },
{ q: "What is the best way to avoid road rage?", a: "Allow plenty of time, be courteous, and avoid cutting others off." },
{ q: "What is 'drowsy driving'?", a: "Driving when tired or sleepy, which slows reaction time and impairs judgment." },
{ q: "When are drivers most likely to fall asleep at the wheel?", a: "Between midnight and 6 a.m. or during long, monotonous drives." },
{ q: "What should you do if you feel drowsy while driving?", a: "Stop safely, rest, or switch drivers." },
{ q: "What is 'impaired driving'?", a: "Driving under the influence of alcohol, drugs, or medication." },
{ q: "What is the legal Blood Alcohol Concentration (BAC) limit for drivers 21 and over?", a: "0.08 percent." },
{ q: "What is the BAC limit for drivers under 21?", a: "0.02 percent or higher is illegal." },
{ q: "Can prescription or over-the-counter drugs impair driving?", a: "Yes — some medications cause drowsiness or slow reactions." },
{ q: "What is the penalty for refusing a chemical test (implied consent law)?", a: "Automatic one-year license suspension." },
{ q: "What is the first-offense penalty for DUI in Virginia?", a: "Fine up to $2,500, up to 12 months in jail, and one-year license suspension." },
{ q: "What happens if a driver under 21 is convicted of DUI?", a: "License suspension for one year and a minimum $500 fine or 50 hours of community service." },
{ q: "What is the penalty for driving while your license is suspended?", a: "Possible jail, extended suspension, and fines." },
{ q: "What is the penalty for leaving the scene of an accident?", a: "Felony charges, fines, and possible prison." },
{ q: "What does 'zero tolerance' mean for underage drinking and driving?", a: "Any measurable alcohol in the system is illegal for drivers under 21." },
{ q: "What is the only safe BAC when driving?", a: "0.00 — no alcohol in your system." },
{ q: "What should you do if your emotions are high before driving?", a: "Calm down before getting behind the wheel." },
{ q: "How does anger affect driving?", a: "It narrows focus and increases risk-taking." },
{ q: "What is the effect of alcohol on judgment?", a: "It reduces your ability to make safe decisions." },
{ q: "What should you do if you’re angry at another driver?", a: "Take a deep breath, slow down, and let them go ahead." },
{ q: "What’s the safest way to deal with stress while driving?", a: "Focus on the road and avoid distractions." },
{ q: "Why is multitasking dangerous while driving?", a: "It divides attention and increases crash risk." },
{ q: "What is a common distraction for new drivers?", a: "Using cellphones and interacting with passengers." },
{ q: "What should you do if you drop something in the car?", a: "Pull over safely before picking it up." },
{ q: "When should you turn on your headlights?", a: "From sunset to sunrise or when visibility is under 500 feet." },
{ q: "Is it safer to drive slower than other traffic?", a: "No — driving much slower can cause crashes; keep with the flow if safe." },
{ q: "Who must wear seat belts in Virginia?", a: "All drivers and front-seat passengers." },
{ q: "Who is responsible for seat-belt use by minors?", a: "The driver." },
{ q: "Are seat belts required in the back seat?", a: "Yes for passengers under 18; adults are strongly encouraged." },
{ q: "What is the safest place for a child in a vehicle?", a: "In the back seat." },
{ q: "At what age must children be secured in a child safety seat?", a: "From birth until age 8." },
{ q: "When can a child face forward in a safety seat?", a: "When they meet the height and weight limits set by the seat’s manufacturer." },
{ q: "When can a child move to a booster seat?", a: "When they outgrow the forward-facing seat (usually around 4 years and 40 lbs)." },
{ q: "When can a child use only a seat belt?", a: "When at least 8 years old and tall enough for the belt to fit properly." },
{ q: "How should a seat belt fit?", a: "Lap belt low across hips; shoulder belt across chest, not neck or face." },
{ q: "Where should rear-facing seats never be placed?", a: "In front of an active airbag." },
{ q: "What is the main purpose of airbags?", a: "To reduce injury in moderate-to-severe crashes." },
{ q: "Can airbags replace seat belts?", a: "No — they work together for best protection." },
{ q: "What should short drivers do for safety with airbags?", a: "Sit at least 10 inches away from the steering wheel." },
{ q: "Should children under 12 sit in front?", a: "No, always in the back seat for safety." },
{ q: "What can happen if airbags deploy while a child is in front?", a: "Serious or fatal injury." },
{ q: "What should pregnant drivers do with seat belts?", a: "Place the lap belt below the belly and shoulder belt across chest." },
{ q: "Are airbags safe for everyone?", a: "Yes when seat belts are worn properly and distance is maintained." },
{ q: "How often should safety seats be replaced after a crash?", a: "Always — even after minor crashes." },
{ q: "What should you check before installing a child seat?", a: "The seat manufacturer’s instructions and vehicle manual." },
{ q: "What organization certifies child-seat safety?", a: "The U.S. Department of Transportation (DOT)." },
{ q: "What happens if you get 12 demerit points in 12 months (under age 18)?", a: "Your license is suspended for 90 days, and you must complete a driver improvement clinic." },
{ q: "What happens after the first demerit point conviction for drivers under 18?", a: "You must complete a driver improvement clinic within 90 days." },
{ q: "What happens after the second demerit point conviction under 18?", a: "License is suspended for 90 days." },
{ q: "What happens after the third demerit point conviction under 18?", a: "License is revoked for one year or until age 18, whichever is longer." },
{ q: "What happens if an adult driver gets 12 demerit points in 12 months?", a: "They may be required to complete a driver improvement clinic." },
{ q: "What happens if an adult driver gets 18 demerit points in 12 months?", a: "License suspension for 90 days and driver improvement clinic required." },
{ q: "How long do demerit points stay on your record?", a: "Two years from the date of the offense." },
{ q: "How many safe driving points can you earn each year?", a: "One point per year with a clean record, up to +5 maximum." },
{ q: "What is the penalty for driving without insurance?", a: "License and registration suspension until insurance proof and fees are provided." },
{ q: "What is the penalty for driving with a suspended license?", a: "Possible jail time, additional suspension, and fines." },
{ q: "What is the penalty for providing false information to DMV?", a: "Fines, suspension, and possible jail time." },
{ q: "What is the penalty for hit and run with injury or death?", a: "Felony charges, license revocation, and imprisonment." },
{ q: "What happens if you refuse a breath or blood test under implied consent law?", a: "Automatic one-year license suspension." },
{ q: "What is the penalty for failing to pay child support?", a: "License suspension until payments are up to date." },
{ q: "What happens if you accumulate too many unpaid toll violations?", a: "DMV can suspend your vehicle registration." },
{ q: "What is the penalty for driving without a license?", a: "Fine up to $1,000 and possible jail up to 6 months." },
{ q: "What is the penalty for littering in Virginia?", a: "Fines up to $2,500 and/or up to 12 months in jail." },
{ q: "What happens if you fail to pay court fines or costs?", a: "License suspension until the debt is cleared or payment plan arranged." },
{ q: "What happens if you don’t appear in court for a traffic ticket?", a: "License suspension until the matter is resolved." },
{ q: "Can you lose your license for drug-related offenses?", a: "Yes, including for possession or distribution." },
{ q: "What must you do if your license is suspended?", a: "Stop driving immediately and comply with reinstatement requirements." },
{ q: "What is a driver improvement clinic?", a: "A DMV-approved course to help drivers correct unsafe habits and regain points." },
{ q: "What happens when your license is revoked?", a: "You must reapply and may need to retake all tests." },
{ q: "What is a restricted license?", a: "A license allowing limited driving for work, school, or medical purposes." },
{ q: "What does CDL stand for?", a: "Commercial Driver’s License." },
{ q: "Who needs a CDL?", a: "Drivers of large, heavy, or hazardous-material vehicles." },
{ q: "What are the CDL classes?", a: "Class A (combination), Class B (single heavy vehicle), and Class C (smaller vehicles carrying passengers or hazardous materials)." },
{ q: "What is the minimum age for a CDL in Virginia?", a: "18 for intrastate driving, 21 for interstate or hazardous materials." },
{ q: "What license is required for a motorcycle?", a: "A motorcycle endorsement (M) or a motorcycle-only license." },
{ q: "What is a motorcycle learner’s permit?", a: "It allows practice riding during daylight on non-highways under supervision." },
{ q: "What is a learner’s permit?", a: "A permit allowing supervised driving while learning, valid for 9 months before applying for a license." },
{ q: "At what age can you get a learner’s permit in Virginia?", a: "15 years and 6 months." },
{ q: "What is a commercial learner’s permit (CLP)?", a: "Allows practice driving a commercial vehicle with a CDL holder present." },
{ q: "What is a REAL ID?", a: "A federally compliant driver’s license or ID card used for airport and federal building access." },
{ q: "When will you need a REAL ID for flying within the U.S.?", a: "Starting May 7, 2025, unless you use a passport." },
{ q: "What must you show to get a REAL ID?", a: "Proof of identity, legal presence, Social Security number, and two Virginia residency documents." },
{ q: "Can you still get a standard Virginia license?", a: "Yes, but it will say 'Not for Federal Identification'." },
{ q: "What is a temporary driver’s license?", a: "A short-term license issued while permanent card is mailed." },
{ q: "How long is a standard driver’s license valid?", a: "Typically 8 years; 5 years if age 75 or older." },
{ q: "When must you renew your license?", a: "Before it expires; renewal can be done up to one year in advance." },
{ q: "Can you renew your license online?", a: "Yes, if you meet DMV eligibility requirements." },
{ q: "When must you carry your driver’s license?", a: "At all times while operating a motor vehicle." },
{ q: "What should you do if your address changes?", a: "Notify DMV within 30 days." },
{ q: "What must you do if your name changes?", a: "Update it at DMV within 30 days and show legal documentation." },
{ q: "What should you do if your license is lost or stolen?", a: "Report it and apply for a duplicate." },
{ q: "What should you do if you move to Virginia?", a: "Obtain a Virginia license within 60 days." },
{ q: "What should you do if you sell your vehicle?", a: "Remove the plates and return them to DMV or transfer them." },
{ q: "When must a vehicle have an inspection?", a: "Annually for safety; emissions every two years in certain localities." },
{ q: "Can you drive with an expired inspection sticker?", a: "No, your vehicle is not legal to drive until inspected." },
{ q: "When must headlights be used?", a: "From sunset to sunrise, and when wipers are on or visibility is poor." },
{ q: "What is the 'Move Over' law?", a: "You must move over or slow down for stopped emergency vehicles with flashing lights." },
{ q: "What is the maximum BAC for DUI for commercial drivers?", a: "0.04 percent." },
{ q: "What is the penalty for open alcohol containers in the vehicle?", a: "Possible fine and evidence of drinking while driving." },
{ q: "When must you yield to emergency vehicles?", a: "Always — pull to the right and stop." },
{ q: "What should you do if you’re involved in an accident?", a: "Stop, assist the injured, exchange information, and report to police if necessary." },
{ q: "When must you report a crash?", a: "If there’s injury, death, or property damage of $1,000 or more." },
{ q: "What should you do if you hit an unattended vehicle?", a: "Stop and leave your name, address, and contact information." },
{ q: "What should you do after a minor crash with no injuries?", a: "Move vehicles off the road if possible and exchange information." },
{ q: "What should you do if your brakes fail?", a: "Pump the brakes, downshift, and use the parking brake slowly." },
{ q: "What should you do if your tires blow out?", a: "Hold the wheel firmly, slow gradually, and steer safely off the road." },
{ q: "What should you do if your car skids?", a: "Steer in the direction you want to go and avoid braking suddenly." },
{ q: "What should you do in fog?", a: "Use low-beam headlights and reduce speed." },
{ q: "What should you do if your car begins to hydroplane?", a: "Ease off the gas and steer straight until traction returns." },
{ q: "When should you use your turn signals?", a: "At least 100 feet before turning or changing lanes." },
{ q: "When should you check your blind spots?", a: "Before changing lanes or merging." },
{ q: "What should you do when driving near bicycles?", a: "Allow at least 3 feet when passing." },
{ q: "Is it legal for cyclists to use the full lane?", a: "Yes, when necessary for safety." },
{ q: "When should you dim your headlights?", a: "Within 500 feet of oncoming traffic or 200 feet when following another car." },
{ q: "When must you stop for a school bus?", a: "Whenever lights flash and the stop sign is extended, unless on a divided highway." },
{ q: "When can you proceed past a stopped school bus?", a: "Only when the bus moves again or signals are off." },
{ q: "What color are warning signs?", a: "Yellow with black symbols or letters." },
{ q: "What does a red sign indicate?", a: "Stop, yield, or prohibited action." },
{ q: "What does an orange sign indicate?", a: "Construction or work zone ahead." },
{ q: "What does a green sign indicate?", a: "Directional guidance or distance information." },
{ q: "What does a blue sign indicate?", a: "Motorist services like gas, food, or rest areas." },
{ q: "What does a brown sign indicate?", a: "Historical, cultural, or recreational points of interest." },
{ q: "What does a white or black sign indicate?", a: "Regulatory information — obey these signs." },
{ q: "What should you always do before driving?", a: "Adjust mirrors, seat, and fasten your seat belt." },
{ q: "What is the 'two-second rule'?", a: "Stay at least two seconds behind the car ahead for safe distance." },
{ q: "What does a solid yellow line mean?", a: "No passing from your lane." },
{ q: "What does a broken yellow line mean?", a: "Passing is allowed when clear." },
{ q: "What do white lines indicate?", a: "Traffic moving in the same direction." },
{ q: "What do double solid white lines mean?", a: "Do not change lanes." },
{ q: "What does a diamond symbol in a lane mean?", a: "Reserved for carpools, buses, or bicycles." },
{ q: "What do blue curb markings mean?", a: "Parking for disabled persons only." },
{ q: "What do red curb markings mean?", a: "No parking, stopping, or standing." },
{ q: "What do yellow curb markings mean?", a: "Loading or unloading zone only." },
{ q: "What should you do before opening your car door on the street?", a: "Check for cyclists and traffic." },
{ q: "What is defensive driving?", a: "Driving to prevent accidents despite others’ mistakes." },
{ q: "What should you do when merging onto a highway?", a: "Match the speed of traffic and merge smoothly." },
{ q: "What should you do if you miss your exit?", a: "Go to the next exit; never back up." },
{ q: "What should you do when your vehicle breaks down?", a: "Pull off the road, turn on hazard lights, and stay inside if unsafe outside." },
{ q: "What should you carry in your vehicle at all times?", a: "License, registration, and proof of insurance." },
{ q: "What should you do before a long trip?", a: "Check tires, brakes, fluids, and lights." },
{ q: "What is the 'Move Over' law in Virginia?", a: "You must change lanes or slow down for stopped emergency or maintenance vehicles." },
{ q: "Who must you yield to in a crosswalk?", a: "Pedestrians." },
{ q: "What does 'yield' mean?", a: "Let others go first when they have the right of way." },
{ q: "What should you always do when you see emergency lights behind you?", a: "Pull over to the right and stop." },
{ q: "What is the most common cause of traffic crashes?", a: "Driver error or inattention." },
{ q: "What should you do if traffic signals are not working?", a: "Treat the intersection as a four-way stop." },
{ q: "What does a flashing red light mean?", a: "Stop completely and proceed when safe." },
{ q: "What does a flashing yellow light mean?", a: "Proceed with caution." },
{ q: "What does a green light mean?", a: "Go if the intersection is clear." },
{ q: "What is the speed limit in a residential area?", a: "25 mph unless otherwise posted." },
{ q: "What does a 'Yield' sign mean?", a: "Slow down and give the right of way before entering." },
{ q: "What should you do if another driver fails to yield?", a: "Be prepared to stop to avoid a crash." },
{ q: "When should headlights be used in fog?", a: "Use low beams." },
{ q: "What should you do in heavy rain?", a: "Slow down and turn on headlights and wipers." },
{ q: "What should you do if your vehicle starts to skid?", a: "Steer in the direction you want to go and avoid braking hard." },
{ q: "What should you do if your accelerator sticks?", a: "Shift to neutral and brake gently." },
{ q: "What should you do if your vehicle catches fire?", a: "Pull over, get out, and move away quickly." },
{ q: "What should you do if your car goes into water?", a: "Unbuckle, roll down or break a window, and escape quickly." },
{ q: "When should you increase following distance?", a: "In bad weather, poor visibility, or behind large vehicles." },
{ q: "What should you always do when approaching a railroad crossing?", a: "Look, listen, and slow down." },
{ q: "When should you stop at railroad tracks?", a: "When lights flash, gates are down, or a train is approaching." },
{ q: "Is it legal to go around lowered railroad gates?", a: "No, it is illegal and deadly." },
{ q: "What should you do if your car stalls on train tracks?", a: "Exit immediately and move toward the train’s direction." },
{ q: "What does a crossbuck sign mean?", a: "It marks a railroad crossing; yield to trains." },
{ q: "What should you do if a police officer signals you to pull over?", a: "Do so safely, stay in your car, and keep your hands visible." },
{ q: "When can you turn right on red?", a: "After a complete stop and if no sign prohibits it, unless pedestrians are crossing." },
{ q: "When can you turn left on red?", a: "From a one-way street onto another one-way street, after a complete stop." },
{ q: "What should you do before entering an intersection?", a: "Check left, right, and ahead for traffic and pedestrians." },
{ q: "When must you use headlights?", a: "From sunset to sunrise or when visibility is under 500 feet." },
{ q: "When must you turn on windshield wipers?", a: "During rain, snow, or sleet." },
{ q: "What is the legal BAC limit for drivers 21+?", a: "0.08 percent." },
{ q: "What happens if you are caught with open alcohol while driving?", a: "You may be charged with drinking while operating a vehicle." },
{ q: "What should you do if your license is suspended for points?", a: "Complete driver improvement and pay reinstatement fees." },
{ q: "When must you yield to school buses?", a: "Always when lights flash and stop arm is extended, unless divided highway." },
{ q: "Who must wear seat belts in Virginia?", a: "Drivers and all passengers under 18." },
{ q: "What should you always carry when driving?", a: "Driver’s license, registration, and insurance proof." },
{ q: "What should you do when an emergency vehicle approaches?", a: "Pull to the right and stop until it passes." },
{ q: "What does a 'No Passing Zone' sign mean?", a: "Do not pass other vehicles in this area." },
{ q: "What does a solid yellow line mean?", a: "No passing from your lane." },
{ q: "What do white lines indicate?", a: "Traffic moving in the same direction." },
{ q: "What do yellow lines indicate?", a: "Traffic moving in opposite directions." },
{ q: "What should you do at a flashing yellow arrow?", a: "Turn with caution and yield to oncoming traffic." },
{ q: "When must you stop for pedestrians?", a: "Always in crosswalks or intersections." },
{ q: "When should you turn on headlights?", a: "From sunset to sunrise or when wipers are on." },
{ q: "When should you reduce speed?", a: "In rain, fog, work zones, or heavy traffic." },
{ q: "What is the best way to avoid crashes?", a: "Stay alert, maintain space, and follow traffic laws." }
  ] //terminar

  const [i, setI] = useState(0);
  const [show, setShow] = useState(false);

  function next() {
    setShow(false);
    setI( (i + 1) % cards.length )
  }
  function atras() {
    setShow(false);
    setI( (i-1 + cards.length) % cards.length );
  }

  return(
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 text-gray-800 p-4">
      <h1 className="text-2xl font-bold mb-6">🚗 DMV Study Guide </h1>

      <div className="bg-white shadow-lg rounded-2xl p-8 max-w-sm w-full text-center" >
        <p className="text-sm text-gray-500 mb-2">
          Question {i+1} of {cards.length}
        </p>
        <h2 className="text-lg font-semibold mb-6">
          {cards[i].q}
        </h2>
      </div>

      {show ? (
        <div className="p-3 mb-4 bg-green-100 rounded-xl font-medium"> {cards[i].a} </div>
      ) : (
        <button onClick={() => setShow(true)} className="px-4 py-2 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700"> 
          Ver Respuesta!
        </button>
      )}

      <div className="mt-4">
        <button onClick={atras}
        className="px-4 py-2 border border-indigo-600 text-indigo-600 rounded-xl hover:bg-indigo-50"
        >
          ← Atrás
        </button>

        <button onClick={next}
        className="px-4 py-2 border border-indigo-600 text-indigo-600 rounded-xl hover:bg-indigo-50"
        >
          Siguiente →
        </button>    
      </div>
    </div>

    
  );
}

